apiVersion: v1
kind: Secret
metadata:
  name: firecrawl-secret
type: Opaque
data:
  OPENAI_API_KEY: ""
  SLACK_WEBHOOK_URL: ""
  LLAMAPARSE_API_KEY: ""
  BULL_AUTH_KEY: ""
  TEST_API_KEY: ""
  POSTHOG_API_KEY: ""
  POSTHOG_HOST: ""
  STRIPE_PRICE_ID_STANDARD: ""
  STRIPE_PRICE_ID_SCALE: ""
  FIRE_ENGINE_BETA_URL: ""
  REDIS_PASSWORD: ""

---

apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IuYms4cyI6eyJ1c2VybmFtZSI6InJvYm90JGpwdWxsIiwicGFzc3dvcmQiOiJRd2VyMTIjJCIsImF1dGgiOiJjbTlpYjNRa2FuQjFiR3c2VVhkbGNqRXlJeVE9In19fQ==
